# Generated by Django 5.2 on 2025-04-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorsubjectrelation',
            unique_together={('instructor', 'subject')},
        ),
        migrations.AddField(
            model_name='instructorstudentrelation',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='instructorstudentrelation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorstudentrelation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='instructorsubjectrelation',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectrelation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectrelation',
            name='start_time',
        ),
    ]
