# Generated by Django 5.2 on 2025-04-14 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_instructorsubjectrelation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(default='13:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
